name: Trigger auto deployment for algorhythm-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/algorhythm-server-AutoDeployTrigger-da169b48-6d06-4b78-88b4-118d61dc84c4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ALGORHYTHMSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ALGORHYTHMSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ALGORHYTHMSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/AlgoRhythm/AlgoRhythm
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.ALGORHYTHMSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALGORHYTHMSERVER_REGISTRY_PASSWORD }}
          containerAppName: algorhythm-server
          resourceGroup: algorhythm-app
          imageToBuild: ghcr.io/algorhythm-server:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


