name: Trigger auto deployment for code-executor

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/code-executor-AutoDeployTrigger-8dfc304f-10f6-4404-be34-659c7702a2af.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
      packages: write

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CODEEXECUTOR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CODEEXECUTOR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CODEEXECUTOR_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/AlgoRhythm
          dockerfilePath: CodeExecutor/Dockerfile
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.CODEEXECUTOR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CODEEXECUTOR_REGISTRY_PASSWORD }}
          containerAppName: code-executor
          resourceGroup: algorhythm-app
          imageToBuild: ghcr.io/algorhythmproject/code-executor:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_







