name: Build and Push Docker Images
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Build backend image
    - name: Build backend
      run: docker build -t ${{ env.REGISTRY }}/algorhythmproject/backend/algorhythm-backend:latest -f ./AlgoRhythm/AlgoRhythm/Dockerfile ./AlgoRhythm
    
    # Push backend image
    - name: Push backend
      run: docker push ${{ env.REGISTRY }}/algorhythmproject/backend/algorhythm-backend:latest
    
    # Build code executor image
    - name: Build code executor
      run: docker build -t ${{ env.REGISTRY }}/algorhythmproject/backend/code-executor:latest -f ./AlgoRhythm/CodeExecutor/Dockerfile ./AlgoRhythm
    
    # Push code executor image
    - name: Push code executor
      run: docker push ${{ env.REGISTRY }}/algorhythmproject/backend/code-executor:latest

    # Deploy pushed images
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Container Apps (backend server)
      run: |
        az containerapp update \
          --name backend \
          --resource-group algorhythm-app \
          --image ${{ env.REGISTRY }}/algorhythmproject/backend/algorhythm-backend:latest

    - name: Deploy to Azure Container Apps (code executor)
      run: |
        az containerapp update \
          --name code-executor \
          --resource-group algorhythm-app \
          --image ${{ env.REGISTRY }}/algorhythmproject/backend/code-executor:latest
