name: Build and Push Docker Images
on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Build backend image
    - name: Build backend
      run: docker build -t ${{ env.REGISTRY }}/algorhythmproject/backend/algorhythm-backend:latest -f ./AlgoRhythm/AlgoRhythm/Dockerfile ./AlgoRhythm
    
    # Push backend image
    - name: Push backend
      run: docker push ${{ env.REGISTRY }}/algorhythmproject/backend/algorhythm-backend:latest
    
    # Build code executor image
    - name: Build code executor
      run: docker build -t ${{ env.REGISTRY }}/algorhythmproject/backend/code-executor:latest -f ./AlgoRhythm/CodeExecutor/Dockerfile ./AlgoRhythm
    
    # Push code executor image
    - name: Push code executor
      run: docker push ${{ env.REGISTRY }}/algorhythmproject/backend/code-executor:latest

     # Build code analyzer image
    - name: Build code executor
      run: docker build -t ${{ env.REGISTRY }}/algorhythmproject/backend/code-analyzer:latest -f ./AlgoRhythm/CodeAnalyzer/Dockerfile ./AlgoRhythm
    
    # Push code analyzer image
    - name: Push code executor
      run: docker push ${{ env.REGISTRY }}/algorhythmproject/backend/code-analyzer:latest

    # Build visualizer image
    - name: Build code executor
      run: docker build -t ${{ env.REGISTRY }}/algorhythmproject/backend/visualizer:latest -f ./AlgoRhythm/visualizerService/Dockerfile ./AlgoRhythm
    
    # Push code executor image
    - name: Push code executor
      run: docker push ${{ env.REGISTRY }}/algorhythmproject/backend/visualizer-executor:latest
