name: CI/CD Pipeline (Backend)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Test & Performance
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore /Algorhythm/Algorhythm.sln

      - name: Build solution
        run: dotnet build /Algorhythm/Algorhythm.sln --configuration Release --no-restore

      # Run Unit Tests
      - name: Run Unit Tests with Coverage
        run: |
            dotnet test /Algorhythm/IntegrationTests/UnitTests/UnitTests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=UnitTestResults.trx" \
            --collect:"XPlat Code Coverage"

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
            name: UnitTestResults
            path: '**/UnitTestResults/*.trx'

      - name: Upload Unit Test Coverage
        uses: actions/upload-artifact@v4
        with:
            name: UnitTestCoverage
            path: '**/UnitTestResults/**/coverage.cobertura.xml'


    # Run Integration Tests
      - name: Run Integration Tests with Coverage
        run: |
            dotnet test /Algorhythm/IntegrationTests/IntegrationTests.csproj \
            --configuration Release \
            --no-build \
            --logger "trx;LogFileName=IntegrationTestResults.trx" \
            --collect:"XPlat Code Coverage"

      - name: Upload Integration Test Results
        uses: actions/upload-artifact@v4
        with:
            name: IntegrationTestResults
            path: '**/IntegrationTestResults/*.trx'

      - name: Upload Integration Test Coverage
        uses: actions/upload-artifact@v4
        with:
            name: IntegrationTestCoverage
            path: '**/IntegrationTestResults/**/coverage.cobertura.xml'

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          organization: ${{ secrets.SONAR_ORG }}
          token: ${{ secrets.SONAR_TOKEN }}

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Scan NuGet packages for vulnerabilities
        run: dotnet list /Algorhythm/Algorhythm.sln package --vulnerable