name: CI/CD Pipeline (Backend)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    name: Build, Test & Performance
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      JWT_KEY: ${{ secrets.JWT_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore AlgoRhythm/AlgoRhythm.sln

      - name: Build solution
        run: dotnet build AlgoRhythm/AlgoRhythm.sln --configuration Release --no-restore

      # Run Unit Tests
      - name: Run Unit Tests with Coverage
        run: >
            dotnet test AlgoRhythm/UnitTests/UnitTests.csproj 
            --configuration Release 
            --logger "trx;LogFileName=UnitTestResults.trx" 
            --collect:"XPlat Code Coverage" 
            /p:CoverletOutputFormat=cobertura 
            /p:Include="[AlgoRhythm.*]*"
            /p:Exclude="[*.Tests]*"

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
            name: UnitTestResults
            path: '**/UnitTests/TestResults/*.trx'

      - name: Upload Unit Test Coverage
        uses: actions/upload-artifact@v4
        with:
            name: UnitTestCoverage
            path: '**/UnitTests/TestResults/**/coverage.cobertura.xml'

      # Run Integration Tests
      - name: Run Integration Tests with Coverage
        run: >
            dotnet test AlgoRhythm/IntegrationTests/IntegrationTests.csproj 
            --configuration Release 
            --logger "trx;LogFileName=IntegrationTestResults.trx" 
            --collect:"XPlat Code Coverage"
            /p:CoverletOutputFormat=cobertura 
            /p:Include="[AlgoRhythm.*]*" 
            /p:Exclude="[*.Tests]*"

      - name: Upload Integration Test Results
        uses: actions/upload-artifact@v4
        with:
            name: IntegrationTestResults
            path: '**/IntegrationTests/TestResults/*.trx'

      - name: Upload Integration Test Coverage
        uses: actions/upload-artifact@v4
        with:
            name: IntegrationTestCoverage
            path: '**/IntegrationTests/TestResults/**/coverage.cobertura.xml'

      # Generate and upload HTML Coverage Report
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Merge Coverage and Generate HTML
        run: >
          mkdir CoverageReport
          reportgenerator 
            -reports:"**/TestResults/**/coverage.cobertura.xml" 
            -targetdir:CoverageReport 
            -reporttypes:Html 
            -sourcedirs:"AlgoRhythm;AlgoRhythm.Shared;CodeExecutor"

      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: CoverageReport
      
